exclude: [README, TODO, vendor]
permalink: /:year/:month/:title
google_analytics: UA-106539450-1
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-default-layout 
